server:
  port: 8081
  servlet:
    context-path: /

limit:
  minMoney: 1
  maxMoney: 500
  description: 最少发${limit.minMoney}元, 不能超过${limit.maxMoney}元

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/luckymoney
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
